swagger: "2.0"
info:
  title: Presidential Spending
  description: Searchable expenditures from [Propublica's Spending at Trump Properties](https://www.propublica.org/datastore/dataset/spending-at-trump-properties) data.
  version: 0.0.1
paths:
  /expenditures:
    get:
      summary: All expendiures
      description: Filter expenditures with the use of queries.
      parameters:
        - in: query
          name: type
          type: string
          description: Do
          required: false
        - in: query
          name: source
          type: string
          required: false
          description: Entity making payment
        - in: query
          name: amount
          type: string
          required: false
          description: Payment amount
        - in: query
          name: purpose_scrubbed
          type: string
          required: false
          description: Scrubbed purpose
        - in: query
          name: property_scrubbed
          type: string
          required: false
          description: Scrubbed property
        - in: query
          name: purpose
          type: string
          required: false
          description: Purpose
        - in: query
          name: property
          type: string
          required: false
          description: Property
        - in: query
          name: city
          type: string
          required: false
          description: City
        - in: query
          name: state
          type: string
          required: false
          description: State
      responses:
        "200":
          description: OK
          schema:
            type: array
            items:
              properties:
                _id:
                  type: string
                type:
                  type: string
                source:
                  type: string
                amount:
                  type: number
                  format: float
                purpose_scrubbed:
                  type: string
                property_scrubbed:
                  type: string
                purpose:
                  type: string
                property:
                  type: string
                city:
                  type: string
                state:
                  type: string
  /distinct:
    get:
      summary: All distinct values
      description: Returns all distinct values for each query parameter.
      responses:
          "200":
            description: OK
            schema:
              type: array
              items:
                properties:
                  type:
                    type: array
                    items:
                      type: string
                  source:
                    type: array
                    items:
                      type: string
                  amount:
                    type: array
                    items:
                      type: number
                      format: float
                  purpose_scrubbed:
                    type: array
                    items:
                      type: string
                  property_scrubbed:
                    type: array
                    items:
                      type: string
                  purpose:
                    type: array
                    items:
                      type: string
                  property:
                    type: array
                    items:
                      type: string
                  city:
                    type: array
                    items:
                      type: string
                  state:
                    type: array
                    items:
                      type: string