swagger: "2.0"
host: propublicatrump-spending.appspot.com
endpoints_api_sergivice: 
  name: propublicatrump-spending.appspot.com
  rollout_strategy: managed
info:
  title: Presidential Spending
  description: Searchable expenditures from [Propublica's Spending at Trump Properties](https://www.propublica.org/datastore/dataset/spending-at-trump-properties) data.
  version: 0.0.1
paths:
  /expenditures:
    get:
      summary: All expendiures
      description: Filter expenditures with the use of queries.
      operationId: getExpenditures
      parameters:
        - in: query
          name: type
          type: string
          description: Type of filing. ( type=FEC )
          required: false
        - in: query
          name: source
          type: string
          required: false
          description: Entity making payment. ( soruce="Donald J. Trump for President, Inc.")
        - in: query
          name: date
          type: string
          required: false
          description: Date. ( date="May 05, 2015" (=, !=, >, <, >=, <=) )
        - in: query
          name: amount
          type: string
          required: false
          description: Payment amount. ( amount=9000 (=, !=, >, <, >=, <=) )
        - in: query
          name: purpose_scrubbed
          type: string
          required: false
          description: Broad purposes. ( purpose_scrubbed=Rent )
        - in: query
          name: property_scrubbed
          type: string
          required: false
          description: Scrubbed property. ( property="Trump Hotel D.C." )
        - in: query
          name: purpose
          type: string
          required: false
          description: Fine-tuned purpose. ( purpose="Beverages for volunteers" )
        - in: query
          name: property
          type: string
          required: false
          description: Property. ( property="Trump Hotel D.C." )
        - in: query
          name: city
          type: string
          required: false
          description: City. ( city="Plam Beach" )
        - in: query
          name: state
          type: string
          required: false
          description: State. ( state=NY (State abbreviations only) )
      responses:
        "200":
          description: OK
          schema:
            type: array
            items:
              type: object
              properties:
                response_total:
                  type: number
                expenditures:
                  type: array
                  items:
                    type: object
                    properties:
                      _id:
                        type: string
                      type:
                        type: string
                      source:
                        type: string
                      date:
                        type: string
                      amount:
                        type: number
                        format: float
                      purpose_scrubbed:
                        type: string
                      property_scrubbed:
                        type: string
                      purpose:
                        type: string
                      property:
                        type: string
                      city:
                        type: string
                      state:
                        type: string
  /distinct:
    get:
      summary: All distinct values
      description: Returns all distinct values for each query parameter.
      operationId: getDistinctValues
      responses:
          "200":
            description: OK
            schema:
              type: array
              items:
                properties:
                  type:
                    type: array
                    items:
                      type: string
                  source:
                    type: array
                    items:
                      type: string
                  amount:
                    type: array
                    items:
                      type: number
                      format: float
                  purpose_scrubbed:
                    type: array
                    items:
                      type: string
                  property_scrubbed:
                    type: array
                    items:
                      type: string
                  purpose:
                    type: array
                    items:
                      type: string
                  property:
                    type: array
                    items:
                      type: string
                  city:
                    type: array
                    items:
                      type: string
                  state:
                    type: array
                    items:
                      type: string